config/routes.rb
# frozen_string_literal: true
Rails.application.routes.draw do
  # samples routes including GET sampes/json, POST samples/import
  resources :samples do
    collection do
      post :import
      get :json
    end
  end
  root to: 'samples#json'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/sample.rb
class Sample < ActiveRecord::Base
  # alias attributes for samples
  alias_attribute :Row, :row
  alias_attribute :'Sample ID', :sample_id
  alias_attribute :'Sample Type', :sample_type
  alias_attribute :Matrix, :matrix
  alias_attribute :Value, :value
  alias_attribute :Units, :units
  alias_attribute :'Test Method', :test_method
  alias_attribute :'Test Manufacturer', :test_manufacturer
  alias_attribute :'Lab Location', :lab_location
  alias_attribute :'Collection Type', :collection_type
  alias_attribute :Age, :age
  alias_attribute :Gender, :gender
  alias_attribute :Volume, :volume
  alias_attribute :new_column_name, :collection_date
  alias_attribute :'Test Date', :test_date
  alias_attribute :'Frozen Date', :frozen_date
  alias_attribute :Box, :box
  alias_attribute :Aliquots, :aliquots

  # generate new csv file containing all Sample columns
  def self.to_csv
    CSV.generate do |csv|
      csv << column_names
      all.each do |sample|
        csv << sample.attributes.values_at(*column_names)
      end
    end
  end

  # import uploaded csv file, creating new rows for Sample
  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      Sample.create! row.to_hash
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true
# Do not inherit from this class unless you know what you're doing
# See ProtectedController and OpenReadController
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  # Force to wants JSON for API
  # before_action :api_request_settings
  # def api_request_settings
  #   request.format = :json
  # end

  # AUTH_PROC = proc do |signed_token, _opts|
  #   token = begin
  #     Rails.application.message_verifier(:signed_token).verify(signed_token)
  #   rescue ActiveSupport::MessageVerifier::InvalidSignature
  #     false
  #   end
  #   User.find_by token: token
  # end
  #
  # # Use Token Authentication
  # include ActionController::HttpAuthentication::Token::ControllerMethods
  # def authenticate
  #   @current_user =
  #     authenticate_or_request_with_http_token(&AUTH_PROC)
  # end
  #
  # # call from actions to get authenticated user (or nil)
  # attr_reader :current_user
  #
  # # call from unauthenticated actions that want current_user if available
  # def set_current_user
  #   # for access to authenticate method
  #   t = ActionController::HttpAuthentication::Token
  #   @current_user = t.authenticate(self, &AUTH_PROC)
  # end

  # Require SSL for deployed applications
  force_ssl if: :ssl_configured?
  def ssl_configured?
    Rails.env.production?
  end

  # Use enhanced JSON serialization
  include ActionController::Serialization

  # return 404 for failed search by id
  rescue_from ActiveRecord::RecordNotFound, with: :record_not_found
  def record_not_found
    render json: { error: { message: 'Not Found' } }, status: :not_found
  end

  # Restrict visibility of these methods
  private :record_not_found #:authenticate, :current_user,  :set_current_user,
  private :ssl_configured? # ,:api_request_settings

  # protected
  #
  #   def request_http_token_authentication(realm = "Application")
  #     self.headers["WWW-Authenticate"] = %(Token realm="#{realm.gsub(/"/, "")}")
  #     render :json => {:error => "HTTP Token: Access denied."}, :status => :unauthorized
  #   end
end

app/controllers/open_read_controller.rb
# frozen_string_literal: true
# Inherit from this class to allow unauthenticate access to read actions
class OpenReadController < ProtectedController
  READ_ACTIONS = [:index, :show].freeze
  skip_before_action :authenticate, only: READ_ACTIONS
  before_action :set_current_user, only: READ_ACTIONS
end

app/controllers/protected_controller.rb
# frozen_string_literal: true
# Inherit from this class to require authenticated access to all actions
class ProtectedController < ApplicationController
  before_action :authenticate
end

app/controllers/samples_controller.rb
class SamplesController < ApplicationController
  before_action :set_sample, only: [:show, :update, :destroy]
  require 'csv'
  require 'json'

  # GET /samples
  # GET /samples.csv
  # GET /samples.json
  def index
    @samples = Sample.all
    respond_to do |format|
      format.html
      format.csv { send_data @samples.to_csv }
      format.json { send_data @samples.to_json }
    end
  end

  # GET /samples/json
  def json
    @samples = Sample.all

    render json: @samples
  end

  # POST /samples
  def import
    Sample.import(params[:file])
    redirect_to root_url, notice: 'Samples imported.'
  end

  # GET /samples/1
  def show
    render json: @sample
  end

  private

  def set_sample
    @sample = Sample.find(params[:id])
  end

  def sample_params
    params[:sample]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/samples_helper.rb
module SamplesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsCsvApi</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/samples/_form.html.erb
<%= form_for(sample) do |f| %>
  <% if sample.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sample.errors.count, "error") %> prohibited this sample from being saved:</h2>

      <ul>
      <% sample.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/samples/edit.html.erb
<h1>Editing Sample</h1>

<%= render 'form', sample: @sample %>

<%= link_to 'Show', @sample %> |
<%= link_to 'Back', samples_path %>

app/views/samples/index.html.erb
<h1>Samples Index</h1>

<br>

<h4>
Download all sample data in CSV file:
<%= link_to "Download CSV", samples_path(format: "csv") %>
</h4>

<h4>
Download all sample data in JSON file:
<%= link_to "Download JSON", samples_path(format: "json") %>
</h4>

<br>

<h2>Import Samples</h2>
<%= form_tag import_samples_path, multipart: true do %>
<%= file_field_tag :file %>
<%= submit_tag "Import" %>
<% end %>
<p id="notice"><%= notice %></p>
<br>

<table>
    <tr>
        <th>Row,</th>
        <th>Sample ID,</th>
        <th>Sample Type,</th>
        <th>Matrix,</th>
        <th>Value,</th>
        <th>Units,</th>
        <th>Test Method,</th>
        <th>Test Manufacturer,</th>
        <th>Lab Location,</th>
        <th>Collection Type,</th>
        <th>Age,</th>
        <th>Gender,</th>
        <th>Volume,</th>
        <th>collection_date,</th>
        <th>Test Date,</th>
        <th>Frozen Date,</th>
        <th>Box,</th>
        <th>Aliquots,</th>
        <th>created_at</th>
    </tr>

    <% @samples.each do | sample | %>
    <tr>
        <td><%= sample.row %></td>
        <td><%= sample.sample_id%></td>
        <td><%= sample.sample_type%></td>
        <td><%= sample.matrix%></td>
        <td><%= sample.value%></td>
        <td><%= sample.units%></td>
        <td><%= sample.test_method%></td>
        <td><%= sample.test_manufacturer%></td>
        <td><%= sample.lab_location%></td>
        <td><%= sample.collection_type%></td>
        <td><%= sample.age%></td>
        <td><%= sample.gender%></td>
        <td><%= sample.volume%></td>
        <td><%= sample.collection_date%></td>
        <td><%= sample.test_date%></td>
        <td><%= sample.frozen_date%></td>
        <td><%= sample.box%></td>
        <td><%= sample.aliquots%></td>
        <td><%= sample.created_at%></td>
    </tr>
    <% end %>
</table>

<!-- <table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @samples.each do |sample| %>
      <tr>
        <td><%= link_to 'Show', sample %></td>
        <td><%= link_to 'Edit', edit_sample_path(sample) %></td>
        <td><%= link_to 'Destroy', sample, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sample', new_sample_path %> -->

app/views/samples/new.html.erb
<h1>New Sample</h1>

<%= render 'form', sample: @sample %>

<%= link_to 'Back', samples_path %>

app/views/samples/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_sample_path(@sample) %> |
<%= link_to 'Back', samples_path %>